### ISSUE TITLE
Inside 4 Problems with Install

### ISSUE THREAD

**Issue by torrison1** [torrison1/inside4sandbox#1]
Здравствуйте, установила xampp 7.2
Но возникли проблемы с запуском сайта выдает ошибки. Я сделала обычный хеллоу ворд в пхп файл - его открыло.
А вот с сайтом выдает следующие ошибки (1 картинка). В кооперации с @Богдан Демьяненко искали примеры устранения этой ошибки пришли к (2 картинка), но ошибки все равно остались (3 картинка). Скорее всего нужно что-то сделать с базой данных в пхпадамине, но мы не знаем как.
Объясните, пожалуйста))

**Comment by torrison1** [comment]
https://github.com/torrison1/inside4sandbox/blob/master/config_default.php => config.php

Make Import of Database in phpMyAdmin (Import):
https://github.com/torrison1/inside4sandbox/blob/master/Inside4/DataBaseModel/ikiev_inside4.sql

Encryption Vars Example:

    'Security' => Array (
        'encryption_salt1' => 'Aaaaa1aa',
        'encryption_salt2' => 'B11bb11b',
        'encryption_salt_length' => 8,
        'encryption_aes_key' => 'Aaaaa11a',
        'encryption_iv_static' => '1111111100abcdef',
        'csrf_token_key' => '1234567890abcdefghiiaabbccddddAA',
        'csrf_token_salt' => '1234567890aaaabbbbccddeeooxxxzOP',
    ),

**Comment by charleeme** [comment]
До этого  были выполнены пункты из двух подсказок и были заполнены поля файла config.php сайт не запускался и была ошибка в 29 строке. Создала внутренний домен на папку сайта и сайт запустился, вот только картинки не подгружаются. При попытке подгрузить картинку на новой вкладке выдае следующее: Warning: require(AppControllers\Public.php): failed to open stream: 

No such file or directory in D:\xampp\htdocs\inside4sandbox\index.php on line 29
Fatal error: require(): Failed opening required 'AppControllers\Public.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\inside4sandbox\index.php on line 29

**Comment by torrison1** [comment]
@charleeme Пришли скрины:
1) Саму папку что там лежит
2) Какой URL открываеш в браузере?
3) Добавь меня в скайп: alex_xandr созвонимся, расшаришь экран и покажешь, на крайняк уже подскажу при созвоне, раскопаем проблему.

Судя по ошибкам, система хочет открыть контроллер /Public/. Но основная директория должна быть в корне, где index.php. Это не Симфони где index.php лежит в папке /Public/

**Comment by torrison1** [comment]
@charleeme также посмотри видео туториалы по установке системы:
https://www.youtube.com/watch?v=wgUtGbPTyxE&list=PLeCs8ahZzxZTO0Nvw6uEtsMin1dHaU2e6

Может там найдешь что у тебя не так.

**Comment by charleeme** [comment]
1.корневая папка:
![image](https://user-images.githubusercontent.com/66950478/84875537-be228780-b08e-11ea-8620-1ee2ed838424.png)
2. http://inside4sandbox.local/ тут же видно что у картинки прописан путь, но этого пути в проекте не существует:
![image](https://user-images.githubusercontent.com/66950478/84875175-494f4d80-b08e-11ea-82b7-4ea479d8454c.png)

Стоит отметить что  картинки, что находятся на вкладке http://inside4sandbox.local/MobileApp/# , и так же иконка сайта отображаюся:
![image](https://user-images.githubusercontent.com/66950478/84876599-1017dd00-b090-11ea-83dc-01449bc7cde6.png)

Если перейти на http://inside4sandbox.local/MobileApp/ то идет вечная загрузка и отображается такой ряд ошибок:
![image](https://user-images.githubusercontent.com/66950478/84876455-e959a680-b08f-11ea-8c1f-732503df9de4.png)

**Comment by torrison1** [comment]
Отлично, Установка Готова! Дальше 2 новых вопроса: 

1) Where are images after Inside 4 Install?
https://github.com/torrison1/inside4sandbox/issues/2

2) Why Mobile PWA not works after Install? 
https://github.com/torrison1/inside4sandbox/issues/3
